### PR TITLE
Normalize ES6 Usage and kill babel

### PR DESCRIPTION
**Pull request by lyzadanger**
Based on our discussion, we've decided not to ship this module in a state that requires babel transform to use it. To this end, I have:

* Removed the `.node-version` (set to `0.12`) from the repo and added an `engines` property to `package.json` of `>=4.0.0`. Updated `README` accordingly.
* Renamed the `gulpfile` in the `test` directory to _not_ be a `babel`-ized version.

**Important**: I ran into a frightening-looking but ultimately innocuous segfault when doing this work, see [this SO thread](http://stackoverflow.com/questions/32470067/gulp-segmentation-fault-11-after-node-4-0-update). It was fixed by nuking my `node_modules` folder and doing a clean reinstall (on `node 4.0.0`).

Can one of you guys try pulling this branch and running a _regular_ `npm install` and see if you can: 

* `cd test`
* `gulp --tasks`

successfully? 

I'm hoping it works okay and _everyone_ isn't going to run into a segfault.

/cc @mrgerardorodriguez

### CODE REVIEW

**Comment by mrgerardorodriguez** [comment]
Taking a look now.

**Comment by erikjung** [comment]
@lyzadanger I got this from the `test` directory:

```
-bash: ./node_modules/.bin/gulp: No such file or directory
```

Which is odd considering my globally installed `gulp-cli`.

**Comment by lyzadanger** [comment]
@erikjung Can you validate that you're getting node `4.0.0` in that test directory? And can you sanity check a `npm ls -g --depth=0`? I presume you do have `gulp-cli` installed globally for 4.0...I do, FWIW, have `gulp` installed globally for 4.0, as well.

**Comment by erikjung** [comment]
@lyzadanger 

```
cd test && node -v && npm ls -g --depth=0
v4.0.0
/opt/nodes/4.0.0/lib
├── generator-cloudfour-core-patternlib@0.1.0 -> /Users/erikjung/Projects/cloudfour/generator-core-patternlib
├── gulp-cli@0.3.0
├── jscs@2.5.1
├── jshint@2.8.0
├── npm@3.3.12
├── sinon@1.17.2
└── yo@1.5.0
```

**Comment by mrgerardorodriguez** [comment]
I'm getting the same thing as @erikjung in the `test/` directory:
```
$ gulp --tasks
-bash: ./node_modules/.bin/gulp: No such file or directory
```

I also ran those commands:
```
$ cd test && node -v && npm ls -g --depth=0
v4.0.0
/opt/nodes/4.0.0/lib
├── generator-cloudfour-core-patternlib@0.1.0 -> /Users/Rodriguez/Development/projects/cloudfour/generator-test/generator-core-patternlib
├── gulp@3.9.0
├── gulp-cli@0.3.0
├── jscs@2.5.1
├── jshint@2.8.0
├── npm@3.4.0
├── package-json-validator@0.6.0
├── sinon@1.17.2
└── yo@1.5.0
```

**Comment by erikjung** [comment]
@lyzadanger Installing `gulp` globally fixes things:

```
core-gulp-tasks/test (chore-normalize-es6) gulp --tasks
[15:56:30] Using gulpfile ~/Projects/cloudfour/core-gulp-tasks/test/gulpfile.js
[15:56:30] Tasks for ~/Projects/cloudfour/core-gulp-tasks/test/gulpfile.js
[15:56:30] ├── assets
[15:56:30] ├── clean
[15:56:30] ├── css
[15:56:30] ├── html
[15:56:30] └── js
```

**Comment by erikjung** [comment]
:+1:

**Comment by mrgerardorodriguez** [comment]
:+1: also worked for me after installing `gulp` globally.

```
$ gulp --tasks
[16:04:37] Using gulpfile ~/Development/projects/cloudfour/repos/core-gulp-tasks/test/gulpfile.js
[16:04:37] Tasks for ~/Development/projects/cloudfour/repos/core-gulp-tasks/test/gulpfile.js
[16:04:37] ├── assets
[16:04:37] ├── clean
[16:04:37] ├── css
[16:04:37] ├── html
[16:04:37] └── js
```

**Pull request merged**
